### ISSUE TITLE
[Bug]: حذف کلمه "نوب" از دیتاست

### ISSUE THREAD

**Issue by mdk1384** [KomeilParseh/Sansorchi#12]
### Commit to Help

سلام و خسته نباشید خدمت سازنده محترم
بنده پیشنهاد می کنم کلمه "نوب" را از دیتاست حذف کنید. چون "نوب" فحش نیست و به افرادی گفته می شود که در بازی یا حرفه ای تازه کار هستند
با تشکر از شما

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by KomeilParseh** [comment]
<div dir="rtl">

 سلام ممد ممنون بابت ایشو شما  بله برخی از لغات بی دلیل اینجا هستن که باید پاک بشن من برخی از اونا رو حذف کردم لطفا زحمت بقیشو هم خودت بکش :))


</div>

**Comment by mdk1384** [comment]
#14

**Comment by KomeilParseh** [comment]
متشکر
